[project]
name = "organisateur-fichiers"
version = "0.1.0"
description = "Outil en ligne de commande qui range les fichiers d'un dossier par catégorie"
readme = "README.md"
authors = [
    { name = "aboubakar", email = "hamadouaboubakar2020@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
organiser = "organisateur_fichiers.cli:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"